export type PageMeta = {
    path: string;
    title: string;
    subtitle?: string;
    breadcrumbs: string[];
    searchPlaceholder?: string;
};

export const PAGE_META: PageMeta[] = [
    {
        path: '/dashboard',
        title: 'Dashboard',
        subtitle: 'Tổng quan vận hành thiết bị, điều chuyển và bảo trì trong toàn hệ thống.',
        breadcrumbs: ['Dashboard'],
        searchPlaceholder: 'Tìm nhanh theo mã máy hoặc tên thiết bị...',
    },
    {
        path: '/assets',
        title: 'Quản Lý Thiết Bị',
        subtitle: 'Tra cứu, cập nhật, điều phối và theo dõi toàn bộ máy móc trong hệ thống.',
        breadcrumbs: ['Dashboard', 'Quản lý máy'],
        searchPlaceholder: 'Tìm theo tên máy, mã máy, serial...',
    },
    {
        path: '/assets/stocktake',
        title: 'Kiểm Kê QR',
        subtitle: 'Quét tem QR tại hiện trường để đối chiếu máy có mặt, thiếu và sai vị trí.',
        breadcrumbs: ['Dashboard', 'Quản lý máy', 'Kiểm kê QR'],
        searchPlaceholder: 'Quét hoặc nhập mã máy...',
    },
    {
        path: '/assets/:id',
        title: 'Chi Tiết Thiết Bị',
        subtitle: 'Theo dõi hồ sơ, trạng thái và lịch sử hoạt động của thiết bị.',
        breadcrumbs: ['Dashboard', 'Quản lý máy', 'Chi tiết'],
        searchPlaceholder: 'Tìm theo tên máy, mã máy, serial...',
    },
    {
        path: '/qr-labels',
        title: 'Quản Lý Tem QR',
        subtitle: 'Tạo tem QR trắng, in hàng loạt và kích hoạt hồ sơ máy từ hiện trường.',
        breadcrumbs: ['Dashboard', 'Quản lý máy', 'Tem QR'],
        searchPlaceholder: 'Tìm theo mã QR hoặc mã lô...',
    },
    {
        path: '/qr-labels/batches/:id/print',
        title: 'In Tem QR',
        subtitle: 'Kiểm tra và in tem QR theo từng lô.',
        breadcrumbs: ['Dashboard', 'Quản lý máy', 'Tem QR', 'In tem'],
        searchPlaceholder: 'Tìm theo mã QR...',
    },
    {
        path: '/qr/:publicId/activate',
        title: 'Kích Hoạt Tem Máy',
        subtitle: 'Tạo hoặc gán hồ sơ máy từ tem QR trắng đã dán ngoài thực tế.',
        breadcrumbs: ['Dashboard', 'Quản lý máy', 'Tem QR', 'Kích hoạt'],
        searchPlaceholder: 'Tìm theo mã máy...',
    },
    {
        path: '/brands',
        title: 'Quản Lý Nhãn Hiệu',
        subtitle: 'Danh mục nhãn hiệu máy được dùng chung trong module quản lý máy.',
        breadcrumbs: ['Dashboard', 'Quản lý máy', 'Nhãn hiệu'],
        searchPlaceholder: 'Tìm theo tên nhãn hiệu...',
    },
    {
        path: '/maintenances',
        title: 'Lịch Trình Bảo Trì',
        subtitle: 'Quản lý kế hoạch, tiến độ và lịch sử bảo trì thiết bị.',
        breadcrumbs: ['Dashboard', 'Bảo trì'],
        searchPlaceholder: 'Tìm theo phiếu bảo trì hoặc tên thiết bị...',
    },
    {
        path: '/transfers',
        title: 'Điều Chuyển Thiết Bị',
        subtitle: 'Kiểm soát luồng di chuyển thiết bị giữa các cơ sở và khu vực.',
        breadcrumbs: ['Dashboard', 'Điều chuyển'],
        searchPlaceholder: 'Tìm theo mã lệnh, tên máy, tuyến chuyển...',
    },
    {
        path: '/borrowings',
        title: 'Giao Dịch Thiết Bị',
        subtitle: 'Theo dõi luồng mượn nội bộ, mượn ngoài và thuê máy trong toàn hệ thống.',
        breadcrumbs: ['Dashboard', 'Giao dịch thiết bị'],
        searchPlaceholder: 'Tìm theo thiết bị, người mượn, đối tác...',
    },
    {
        path: '/borrowings/new',
        title: 'Tạo Giao Dịch Thiết Bị',
        subtitle: 'Khởi tạo giao dịch mượn hoặc thuê máy mới.',
        breadcrumbs: ['Dashboard', 'Giao dịch thiết bị', 'Tạo mới'],
        searchPlaceholder: 'Tìm theo thiết bị...',
    },
    {
        path: '/borrowings/:id',
        title: 'Chi Tiết Giao Dịch',
        subtitle: 'Xem đầy đủ thông tin và timeline của giao dịch thiết bị.',
        breadcrumbs: ['Dashboard', 'Giao dịch thiết bị', 'Chi tiết'],
        searchPlaceholder: 'Tìm theo thiết bị...',
    },
    {
        path: '/storage',
        title: 'Kho Và Lưu Trữ',
        subtitle: 'Theo dõi vật tư, phụ tùng và máy móc đang lưu trữ trong kho.',
        breadcrumbs: ['Dashboard', 'Kho lưu trữ'],
        searchPlaceholder: 'Tìm theo mã kho, vị trí lưu trữ, thiết bị...',
    },
    {
        path: '/plants',
        title: 'Quản Lý Cơ Sở',
        subtitle: 'Danh mục cơ sở dùng chung cho máy móc, điều chuyển và các luồng vận hành.',
        breadcrumbs: ['Dashboard', 'Cơ sở'],
        searchPlaceholder: 'Tìm theo tên cơ sở, mã cơ sở, địa chỉ...',
    },
    {
        path: '/users',
        title: 'Người Dùng Hệ Thống',
        subtitle: 'Quản lý tài khoản, vai trò và trạng thái truy cập của người dùng.',
        breadcrumbs: ['Dashboard', 'Người dùng'],
        searchPlaceholder: 'Tìm theo tên, email, số điện thoại...',
    },
    {
        path: '/materials',
        title: 'Danh Mục Vật Tư',
        subtitle: 'Quản lý danh mục vật tư dùng chung cho mua sắm, tồn kho và cấp phát trong hệ thống.',
        breadcrumbs: ['Dashboard', 'Quản lý vật tư', 'Danh mục vật tư'],
        searchPlaceholder: 'Tìm theo tên vật tư, mã vật tư...',
    },
    {
        path: '/materials/suppliers',
        title: 'Nhà Cung Cấp Vật Tư',
        subtitle: 'Quản lý danh sách nhà cung cấp, trạng thái hợp tác và lịch sử mua vật tư.',
        breadcrumbs: ['Dashboard', 'Quản lý vật tư', 'Nhà cung cấp'],
        searchPlaceholder: 'Tìm theo tên nhà cung cấp, mã NCC...',
    },
    {
        path: '/materials/inventory',
        title: 'Tồn Kho Vật Tư',
        subtitle: 'Theo dõi số lượng tồn, ngưỡng tối thiểu và biến động vật tư theo từng cơ sở.',
        breadcrumbs: ['Dashboard', 'Quản lý vật tư', 'Tồn kho'],
        searchPlaceholder: 'Tìm theo tên vật tư, mã vật tư...',
    },
    {
        path: '/materials/purchase-requests',
        title: 'Đề Xuất Mua Vật Tư',
        subtitle: 'Quản lý luồng đề xuất mua vật tư từ khởi tạo, phê duyệt đến tổng hợp đặt hàng.',
        breadcrumbs: ['Dashboard', 'Quản lý vật tư', 'Đề xuất mua'],
        searchPlaceholder: 'Tìm theo mã phiếu, cơ sở, người tạo...',
    },
    {
        path: '/materials/purchase-orders',
        title: 'Đặt Hàng Vật Tư',
        subtitle: 'Theo dõi đơn đặt hàng vật tư, nhà cung cấp và trạng thái nhận hàng.',
        breadcrumbs: ['Dashboard', 'Quản lý vật tư', 'Đặt hàng'],
        searchPlaceholder: 'Tìm theo mã đơn, nhà cung cấp...',
    },
    {
        path: '/materials/distributions',
        title: 'Cấp Phát Vật Tư',
        subtitle: 'Kiểm soát luồng cấp phát vật tư giữa các cơ sở và xác nhận đã nhận hàng.',
        breadcrumbs: ['Dashboard', 'Quản lý vật tư', 'Cấp phát'],
        searchPlaceholder: 'Tìm theo mã phiếu, cơ sở gửi, cơ sở nhận...',
    },
    {
        path: '/materials/reports',
        title: 'Báo Cáo Vật Tư',
        subtitle: 'Theo dõi mua vật tư, cấp phát, tồn kho, nhà cung cấp và biến động giá theo thời gian/cơ sở.',
        breadcrumbs: ['Dashboard', 'Quản lý vật tư', 'Báo cáo'],
        searchPlaceholder: 'Tìm theo vật tư, nhà cung cấp...',
    },
    {
        path: '/reports/facility-costs',
        title: 'Báo Cáo Chi Phí Vận Hành',
        subtitle: 'Tổng hợp chi phí vận hành theo cơ sở, gồm vật tư đã cấp phát và chi phí sửa ngoài đã hoàn tất.',
        breadcrumbs: ['Dashboard', 'Báo cáo', 'Chi phí vận hành'],
        searchPlaceholder: 'Tìm theo cơ sở, máy hoặc kỳ báo cáo...',
    },
];
